CREATE DATABASE EMPLOYEE

USE EMPLOYEE

CREATE TABLE DEPARTMENTS
(
  ID INT PRIMARY KEY,
  DEPARTMENTNAME NVARCHAR(100) NOT NULL CHECK(LEN(DEPARTMENTNAME)>2)
)

CREATE TABLE EMPLOYEES
(
 ID INT PRIMARY KEY,
 FULLNAME NVARCHAR(100) NOT NULL CHECK(LEN(FULLNAME)>3),
 SALARY MONEY CHECK (SALARY>0),
 DEPARTMENTID int references DEPARTMENTS(ID)
)